[project]
name = "auto_flow"
version = "0.1.0"
requires-python = ">=3.12, <3.14"
dependencies = [
    "pk-system",
]

[tool.uv.sources]
pk-system = { git = "https://github.com/PARK4139/pk_system.git" }
