[project]
name = "auto_flow"
version = "0.1.0"
requires-python = ">=3.12, <3.14"
dependencies = [
    "pytest",
    "pytest-ordering",
    "pluggy",
    "clipboard>=0.0.4",
    "beautifulsoup4>=4.14.3",
    "selenium>=4.39.0",
]
